/**
 * Build script to bundle all TypeScript modules into a single main.js
 * Uses esbuild to resolve imports and create one combined file
 */

const esbuild = require('esbuild');
const fs = require('fs');

async function buildRuntime() {
  console.log('🔨 Building Nakama runtime from runtime-entry.ts...');

  try {
    // Bundle all TypeScript files starting from runtime-entry.ts
    const result = await esbuild.build({
      entryPoints: ['data/modules/runtime-entry.ts'],
      bundle: true,
      outfile: 'data/modules/main.js',
      platform: 'neutral', // Plain JavaScript, no Node.js/browser assumptions
      target: 'es2020',
      format: 'iife', // Immediately Invoked Function Expression
      globalName: '__NAKAMA_BUNDLE__',
      minify: false,
      sourcemap: false,
      logLevel: 'info',
      banner: {
        js: '// Nakama MMORPG Runtime - Auto-generated bundle\n// Do not edit this file directly - edit runtime-entry.ts and rebuild\n',
      },
    });

    console.log('📦 Bundle created successfully');

    // Post-process: unwrap the IIFE to expose functions globally
    console.log('🔧 Unwrapping IIFE to expose functions globally...');

    let bundleContent = fs.readFileSync('data/modules/main.js', 'utf8');

    // Remove the IIFE wrapper
    bundleContent = bundleContent
      .replace(/var __NAKAMA_BUNDLE__ = \(\(\) => \{\s*/m, '') // Remove opening
      .replace(/\}\)\(\);?\s*$/m, ''); // Remove closing (with optional semicolon)

    // Write back
    fs.writeFileSync('data/modules/main.js', bundleContent);

    console.log('✅ Runtime bundle created: data/modules/main.js');

    // Get file size
    const stats = fs.statSync('data/modules/main.js');
    console.log(`📊 Bundle size: ${(stats.size / 1024).toFixed(2)} KB`);

  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}

buildRuntime();
