extends Node2D

## LootContainer Entity
##
## Task: 5.5 - Implement Loot Container System
## Requirements: 9 (Loot Generation and Drops)
## Design: LootContainer.tscn (lines 426-445)
##
## Spawned at NPC death position, contains loot items generated by server.
## Opens LootPanel on click, despawns when empty.

@onready var sprite = $Sprite2D
@onready var area = $Area2D

# Container state
var container_id: String = ""
var loot_items: Array = []
var is_initialized: bool = false

func _ready():
	# Placeholder visual (will be replaced with actual loot chest sprite)
	sprite.texture = create_placeholder_texture()

func initialize(loot_data: Array, spawn_position: Vector2, npc_template_id: String = ""):
	"""Initialize container with loot items and position"""
	loot_items = loot_data
	position = spawn_position
	container_id = "loot_" + str(Time.get_ticks_msec()) + "_" + npc_template_id
	is_initialized = true

	update_visual()

func create_placeholder_texture() -> Texture2D:
	"""Create a simple placeholder texture for loot container"""
	var image = Image.create(32, 32, false, Image.FORMAT_RGBA8)
	image.fill(Color(0.8, 0.6, 0.2, 1.0))  # Gold/brown color
	return ImageTexture.create_from_image(image)

func update_visual():
	"""Update container appearance based on loot rarity"""
	if loot_items.is_empty():
		return

	# Change color based on highest rarity item
	var highest_rarity = "common"
	for item in loot_items:
		var rarity = item.get("rarity", "common")
		if rarity == "legendary":
			highest_rarity = "legendary"
		elif rarity == "epic" and highest_rarity != "legendary":
			highest_rarity = "epic"
		elif rarity == "rare" and highest_rarity not in ["epic", "legendary"]:
			highest_rarity = "rare"
		elif rarity == "uncommon" and highest_rarity == "common":
			highest_rarity = "uncommon"

	# Apply rarity color to sprite (glow effect)
	var rarity_colors = {
		"common": Color(0.6, 0.6, 0.6),
		"uncommon": Color(0.1, 0.8, 0.1),
		"rare": Color(0.2, 0.5, 1.0),
		"epic": Color(0.6, 0.2, 0.9),
		"legendary": Color(1.0, 0.5, 0.0)
	}
	sprite.modulate = rarity_colors.get(highest_rarity, Color.WHITE)

func _on_area_2d_input_event(_viewport, event, _shape_idx):
	"""Handle click on loot container"""
	if event is InputEventMouseButton:
		if event.pressed and event.button_index == MOUSE_BUTTON_LEFT:
			open_loot_panel()

func open_loot_panel():
	"""Open loot panel to display items"""
	if not is_initialized or loot_items.is_empty():
		return

	# Find LootPanel in Zone scene
	var zone = get_tree().get_root().get_node_or_null("Zone")
	if zone:
		var loot_panel = zone.get_node_or_null("UILayer/Control/LootPanel")
		if loot_panel:
			loot_panel.display_loot(loot_items, self)
		else:
			print("[LootContainer] Error: LootPanel not found in Zone")

func take_item(item_id: String) -> bool:
	"""Remove item from container (called by LootPanel)"""
	var item_index = -1
	for i in range(loot_items.size()):
		if loot_items[i].get("id", "") == item_id:
			item_index = i
			break

	if item_index >= 0:
		loot_items.remove_at(item_index)

		# Despawn if empty
		if loot_items.is_empty():
			despawn()
		else:
			update_visual()

		return true

	return false

func despawn():
	"""Remove container from scene"""
	queue_free()
